#!/bin/bash
set -o pipefail

CONFIG_PATH="tools/"
REPORT_PATH="tools/reports/"

CHANGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.py$')

poetry run ruff format --config=$CONFIG_PATH'ruff.toml' $CHANGED_PY_FILES > $REPORT_PATH'ruff_precommit.ansi'
poetry run ruff check --config=$CONFIG_PATH'ruff.toml' $CHANGED_PY_FILES >> $REPORT_PATH'ruff_precommit.ansi'
poetry run mypy check --config-file=$CONFIG_PATH'mypy.ini' $CHANGED_PY_FILES > $REPORT_PATH'mypy_precommit.ansi'

git add $CHANGED_PY_FILES
