# mypy.ini

[mypy]
mypy_path = ../
exclude = (?x)(
    .*tools/.*    # tools
    | .*env/.*    # any venv
    | .*mypy_cache/.*    # caches
    | .*ruff_cache/.*
    | .*pytest_cache/.*
    | .*__pycache__/.*
    | .*tests/.*  # type checking in tests is unnecessary
  )
exclude_gitignore = True

platform = 'linux'
python_version = 3.9

# Warn about config errors in this file
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True

# checking configurations
warn_unreachable = True
implicit_optional = False

# check for correct type annotations
disallow_untyped_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
strict_equality = True

# error configurations
disable_error_code = attr-defined
enable_error_code =
  truthy-bool,
  truthy-iterable,
  redundant-expr,
  unused-awaitable,
  ignore-without-code,
  possibly-undefined,
  redundant-self,
  explicit-override,
  unimported-reveal,
  deprecated

# Report files
pretty = True
show_error_code_links = True
color_output = True
show_traceback = True
show_error_context = True
show_column_numbers = True
error_summary = True

lineprecision_report = tools/reports/mypy/
linecoverage_report = tools/reports/mypy/
linecount_report = tools/reports/mypy/
any_exprs_report = tools/reports/mypy/
html_report = tools/reports/mypy/
