preview = false
fix = true
unsafe-fixes = false
target-version = "py39"
line-length = 88                                                      # consistent with blacks default
extend-exclude = ["tools", ".vscode", ".pytest_cache", "__pycache__"]
output-format = "full"

[lint]

select = [
  "A",    # flake8-builtins
  "ANN",  # flake8-type-annotations
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "COM",  # flake8-commas
  "CPY",  # flake8-copyright
  "D",    # pydocstyle
  "DJ",   # flake8-django
  "DOC",  # pydoclint
  "DTZ",  # flake8-datetimez
  "E4",   # pycodestyle default
  "E7",   # pycodestyle default
  "E9",   # pycodestyle default
  "ERA",  # flake8-eradicate
  "EXE",  # flake8-executable
  "F",    # pyflakes
  "FA",   # flake8-future-annotations
  "FBT",  # flake8-boolean-trap
  "FLY",  # pyflint
  "FURB", # refurb
  "G",    # flake8-logging-format
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "INP",  # flake8-no-pep420
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",    # pep8-naming
  "PERF", # perflint
  "PGH",  # pygrep-hooks
  "PIE",  # flake8-pie
  "PL",   # pylint
  "PT",   # flake8-pytest-style
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # ruff
  "S",    # flake8-bandit
  "SIM",  # flake8-simpify
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "T20",  # flake8-print
  "T10",  # flake8-debugger
  "TC",   # flake8-type-checking
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]
ignore = [
  "ARG001", # allow unaccessed args
  "ARG002", # allow unaccessed args
  "D100",   # no module docstrings needed
  "COM812", # trailing comma, redundant with `black`
  "D202",   # allow blank line after function docstring
  "D203",   # no blank line before class docstring
  "D205",   # docstring summary can span more than one line
  "D401",   # docstring does not need to be imperative
  "D417",   # must be disabled for google style docs
  "ISC003", # prefer explicit string concat over implicit concat
  "N999",   # module names can be PascalCase too
  "PLR09",  # we have our own complexity rules
  "TRY003", # long exception messages from `tryceratops`
]
external = ["WPS"]

mccabe.max-complexity = 6
[lint.pydocstyle]
convention = "google"

[lint.isort]
# known-first-party = ['core', 'api', 'web', 'gesetze-im-internet']
# known-local-folder = ['core', 'api', 'web', 'gesetze-im-internet']
lines-after-imports = 2

[lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-copyright]
notice-rgx = "# SPDX-License-Identifier: EUPL-1\\.1\n# Copyright \\(C\\) 2025 David Aderbauer\n#\n# This program is free software: you can redistribute it and/or modify\n# it under the terms of the European Union Public License Version 1\\.1 as\n# published by the European Union\\.\n#\n# You should have received a copy of the European Union Public License Version 1\\.1\n# along with this program\\. If not, see <https://spdx.org/licenses/>\\.\n"

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
parametrize-values-row-type = "tuple"
parametrize-values-type = "list"

[lint.per-file-ignores]
"/**/tests/**" = [ # ignores for all test files
  "SLF001",  # private accessed
  "PLR2004", # magic numbers
  "ANN",     # no type annotations in tests needed
  "N802",    # class names must be allowed as part of test function names
  "N803",    # class names must be allowed as part of fixture names
  "N806",    # class names must be allowed as part of mock names
]

[lint.extend-per-file-ignores]
"/**/tests/**/test_**.py" = [ # extend ignores for test_* files, so excluding conftests
  "S101", # asserts
  "F401", # unused import
  "F811", # redefinition of unused
]
